version: '3.0'
services:
  php:
    container_name: php-yii2blog
    build: ./
    volumes:
      - './:/var/www/html'
    
  composer:
    container_name: composer-yii2blog
    image: composer
    command:
      - "composer"
      - "install"
    volumes:
      - './:/web'
  server:
    container_name: nginx-yii2blog
    image: nginx
    depends_on:
      - php
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html'
      - './config/nginx.conf:/etc/nginx/nginx.conf'
  database:
    container_name: postgre-yii2blog
    image: postgres
    depends_on:
      - server
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/db
      PGCLIENTENCODING: UTF8
    ports:
      - '6543:5432'